
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export const grades: string[] = [
/* do not edit */     "Lehrerin / Lehrer",
/* do not edit */     "Studienseminar 19 / 21",
/* do not edit */     "Studienseminar 20 / 22",
/* do not edit */     "Studienseminar 21 / 23",
/* do not edit */     "Eltern",
/* do not edit */     "RAVK",
/* do not edit */     "5a",
/* do not edit */     "5b",
/* do not edit */     "5c",
/* do not edit */     "5d",
/* do not edit */     "5e",
/* do not edit */     "5f",
/* do not edit */     "6a",
/* do not edit */     "6b",
/* do not edit */     "6c",
/* do not edit */     "6d",
/* do not edit */     "6e",
/* do not edit */     "6f",
/* do not edit */     "7a",
/* do not edit */     "7b",
/* do not edit */     "7c",
/* do not edit */     "7d",
/* do not edit */     "7e",
/* do not edit */     "7f",
/* do not edit */     "8a",
/* do not edit */     "8b",
/* do not edit */     "8c",
/* do not edit */     "8d",
/* do not edit */     "8e",
/* do not edit */     "8f",
/* do not edit */     "9a",
/* do not edit */     "9b",
/* do not edit */     "9c",
/* do not edit */     "9d",
/* do not edit */     "9e",
/* do not edit */     "9f",
/* do not edit */     "10a",
/* do not edit */     "10b",
/* do not edit */     "10c",
/* do not edit */     "10d",
/* do not edit */     "10e",
/* do not edit */     "10f",
/* do not edit */     "Q11",
/* do not edit */     "Q12"
/* do not edit */ ];