
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ // tslint:disable-next-line
/* do not edit */ export module data {
/* do not edit */     export interface City {
/* do not edit */         name: string;
/* do not edit */         country: string;
/* do not edit */         distance: number;
/* do not edit */         x: number;
/* do not edit */         y: number;
/* do not edit */         year: number;
/* do not edit */         text: string;
/* do not edit */         isSummer: boolean;
/* do not edit */         angleCCW?: boolean;
/* do not edit */         left?: boolean;
/* do not edit */         isEasternEndpoint?: boolean;
/* do not edit */         isWesternStartpoint?: boolean;
/* do not edit */         image?: string;
/* do not edit */     }
/* do not edit */ 
/* do not edit */     export interface Round {
/* do not edit */         id: number;
/* do not edit */         startDate: Date;
/* do not edit */         text: string;
/* do not edit */         postText: string;
/* do not edit */         cities: City[];
/* do not edit */     }
/* do not edit */ 
/* do not edit */     export interface Country {
/* do not edit */         code: string;
/* do not edit */         name: string;
/* do not edit */     }
/* do not edit */ 
/* do not edit */     export const rounds: Round[] = [
/* do not edit */         {
/* do not edit */             id: 1,
/* do not edit */             postText: `<p>Schön, dass Du so fleißig mitgemacht hast! Die erste Runde von AGtiv ist leider nun schon vorbei.</p>
/* do not edit */             <p>Du findest alle Leistungen und Ergebnisse in der <a href="/scores">Bestenliste</a>.</p>
/* do not edit */             <div class="alert alert-primary">
/* do not edit */                 <h5>Es gibt noch eine zweite Runde mit neuen Zielen!</h5>
/* do not edit */                 <p>Sie beginnt am <b>Samstag, 30. Mai</b>.</p>
/* do not edit */             </div>`,
/* do not edit */             startDate: new Date("2021-04-28"),
/* do not edit */             text: `<p>- Das AG radelt, rollert und läuft gemeinsam einmal um die Welt! -</p><p>Ziel unseres Projekts <b><i>AG</i>tiv</b> ist es, eine Abwechslung zum momentan sehr bewegungsarmen Home School Alltag zu bieten und auch in Zeiten des social distancing den Gemeinschaftsgeist am Allgäu-Gymnasium zu pflegen. </p>
/* do not edit */             <p>Mit einer <b>sportlichen Gemeinschaftsleistung</b> der gesamten Schulfamilie wollen wir versuchen, einmal virtuell die Welt zu umrunden! Aktuell leisten <span class="badge badge-primary fakebadge">{{userCount}} Teilnehmer</span> ihren
/* do not edit */                 Beitrag für dieses Ziel.
/* do not edit */             </p>
/* do not edit */             <p>Jedes Mitglied der Schulfamilie - egal ob Radler, Läufer oder Inliner/Skiroller - kann jeden Tag einen kleinen Beitrag dazu leisten. Näheres erfahrt Ihr in den Regeln. </p>
/* do not edit */             <p>Zum Mitmachen eingeladen sind alle Schülerinnen und Schüler, deren Eltern und sowie alle Lehrkräfte am Allgäu-Gymnasium. Viel Spaß beim Trainieren! </p>
/* do not edit */             <p>Eure Fachschaft Sport</p>`,
/* do not edit */             cities: [
/* do not edit */                 {
/* do not edit */                     name: "Kempten",
/* do not edit */                     country: "de",
/* do not edit */                     distance: 0,
/* do not edit */                     x: 1183,
/* do not edit */                     y: 426,
/* do not edit */                     year: 0,
/* do not edit */                     text: "Hier geht's los!",
/* do not edit */                     isSummer: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Olympia",
/* do not edit */                     country: "gr",
/* do not edit */                     distance: 964,
/* do not edit */                     x: 1159,
/* do not edit */                     y: 462,
/* do not edit */                     year: 1350,
/* do not edit */                     text: "Hier waren die ersten Spiele, blablabla",
/* do not edit */                     isSummer: true,
/* do not edit */                 },
/* do not edit */             ],
/* do not edit */         }
/* do not edit */     ]
/* do not edit */ 
/* do not edit */     export const countries: Country[] = [
/* do not edit */         {
/* do not edit */             code: "ae",
/* do not edit */             name: "Ver. arab. Emirate"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "af",
/* do not edit */             name: "Afghanistan"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ao",
/* do not edit */             name: "Angola"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ar",
/* do not edit */             name: "Argentinien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "au",
/* do not edit */             name: "Australien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "az",
/* do not edit */             name: "Aserbaidschan"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "bg",
/* do not edit */             name: "Bulgarien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "bj",
/* do not edit */             name: "Benin"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "bn",
/* do not edit */             name: "Brunei"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "bo",
/* do not edit */             name: "Bolivien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "br",
/* do not edit */             name: "Brasilien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "bt",
/* do not edit */             name: "Bhutan"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "by",
/* do not edit */             name: "Weißrussland"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ca",
/* do not edit */             name: "Kanada"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cd",
/* do not edit */             name: "D. R. Kongo"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cd",
/* do not edit */             name: "Demokratische Republik Kongo"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cg",
/* do not edit */             name: "Kongo"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ch",
/* do not edit */             name: "Schweiz"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ci",
/* do not edit */             name: "Cote d`Ivoir"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ck",
/* do not edit */             name: "Cookinseln"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cl",
/* do not edit */             name: "Chile"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cm",
/* do not edit */             name: "Kamerun"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cn",
/* do not edit */             name: "China"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cn",
/* do not edit */             name: "Tibet"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "co",
/* do not edit */             name: "Kolumbien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cr",
/* do not edit */             name: "Costa Rica"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cu",
/* do not edit */             name: "Kuba"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "de",
/* do not edit */             name: "Deutschland"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "dj",
/* do not edit */             name: "Dschibouti"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "dk",
/* do not edit */             name: "Dänemark"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "dz",
/* do not edit */             name: "Algerien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ec",
/* do not edit */             name: "Ecuador"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "eh",
/* do not edit */             name: "Westsahara"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "es",
/* do not edit */             name: "Spanien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "et",
/* do not edit */             name: "Äthiopien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "fi",
/* do not edit */             name: "Finnland"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "fj",
/* do not edit */             name: "Fidschi"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "fr",
/* do not edit */             name: "Frankreich"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ga",
/* do not edit */             name: "Gabun"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ge",
/* do not edit */             name: "Georgien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gf",
/* do not edit */             name: "Franz. Guyana"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gh",
/* do not edit */             name: "Ghana"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gi",
/* do not edit */             name: "Gibraltar"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gl",
/* do not edit */             name: "Grönland"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gn",
/* do not edit */             name: "Guinea"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gt",
/* do not edit */             name: "Guatemala"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gy",
/* do not edit */             name: "Guyana"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "hk",
/* do not edit */             name: "Hongkong"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "hn",
/* do not edit */             name: "Honduras"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "hr",
/* do not edit */             name: "Kroatien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ht",
/* do not edit */             name: "Haiti"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "id",
/* do not edit */             name: "Indonesien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "in",
/* do not edit */             name: "Indien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ir",
/* do not edit */             name: "Iran"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "is",
/* do not edit */             name: "Island"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "it",
/* do not edit */             name: "Italien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "jp",
/* do not edit */             name: "Japan"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ke",
/* do not edit */             name: "Kenia"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "kh",
/* do not edit */             name: "Kambodscha"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "kr",
/* do not edit */             name: "Südkorea"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ma",
/* do not edit */             name: "Marokko"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "mm",
/* do not edit */             name: "Myanmar"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "mw",
/* do not edit */             name: "Malawi"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "mx",
/* do not edit */             name: "Mexiko"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "mz",
/* do not edit */             name: "Mosambik"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "na",
/* do not edit */             name: "Namibia"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ne",
/* do not edit */             name: "Niger"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ng",
/* do not edit */             name: "Nigeria"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ni",
/* do not edit */             name: "Nicaragua"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "no",
/* do not edit */             name: "Norwegen"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "np",
/* do not edit */             name: "Nepal"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "nz",
/* do not edit */             name: "Neuseeland"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "om",
/* do not edit */             name: "Oman"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "pa",
/* do not edit */             name: "Panama"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "pe",
/* do not edit */             name: "Peru"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "pf",
/* do not edit */             name: "Französisch-Polynesien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ph",
/* do not edit */             name: "Philippinen"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "pk",
/* do not edit */             name: "Pakistan"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "pl",
/* do not edit */             name: "Polen"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "pn",
/* do not edit */             name: "Piticairninseln"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "py",
/* do not edit */             name: "Paraguay"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "rs",
/* do not edit */             name: "Serbien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ru",
/* do not edit */             name: "Russland"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "se",
/* do not edit */             name: "Schweden"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "sh",
/* do not edit */             name: "St. Helena"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "sl",
/* do not edit */             name: "Sierra Leone"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "sn",
/* do not edit */             name: "Senegal"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "sr",
/* do not edit */             name: "Suriname"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ss",
/* do not edit */             name: "Südsudan"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "td",
/* do not edit */             name: "Tschad"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "th",
/* do not edit */             name: "Thailand"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "tl",
/* do not edit */             name: "Osttimor"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "tm",
/* do not edit */             name: "Turkmenistan"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "tn",
/* do not edit */             name: "Tunesien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "to",
/* do not edit */             name: "Tonga"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "tr",
/* do not edit */             name: "Türkei"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "tw",
/* do not edit */             name: "Taiwan"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "tz",
/* do not edit */             name: "Tansania"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "us",
/* do not edit */             name: "USA"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "uy",
/* do not edit */             name: "Uruguay"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ve",
/* do not edit */             name: "Venezuela"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "vn",
/* do not edit */             name: "Vietnam"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ws",
/* do not edit */             name: "Samoa"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "za",
/* do not edit */             name: "Südafrika"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "zw",
/* do not edit */             name: "Simbabwe"
/* do not edit */         },
/* do not edit */     ];
/* do not edit */ }
/* do not edit */