
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ // tslint:disable-next-line
/* do not edit */ export module data {
/* do not edit */     export interface City {
/* do not edit */         name: string;
/* do not edit */         country: string;
/* do not edit */         distance: number;
/* do not edit */         x: number;
/* do not edit */         y: number;
/* do not edit */         angleCCW?: boolean;
/* do not edit */         left?: boolean;
/* do not edit */         isEasternEndpoint?: boolean;
/* do not edit */         isWesternStartpoint?: boolean;
/* do not edit */         image?: string;
/* do not edit */     }
/* do not edit */
/* do not edit */     export interface Round {
/* do not edit */         id: number;
/* do not edit */         startDate: Date;
/* do not edit */         text: string;
/* do not edit */         postText: string;
/* do not edit */         cities: City[];
/* do not edit */     }
/* do not edit */
/* do not edit */     export interface Country {
/* do not edit */         code: string;
/* do not edit */         name: string;
/* do not edit */     }
/* do not edit */
/* do not edit */     export const rounds: Round[] = [
/* do not edit */         {
/* do not edit */             id: 1,
/* do not edit */             postText: `<p>Schön, dass Du so fleißig mitgemacht hast! Die erste Runde von AGtiv ist leider nun schon vorbei.</p>
/* do not edit */             <p>Du findest alle Leistungen und Ergebnisse in der <a href="/scores">Bestenliste</a>.</p>
/* do not edit */             <div class="alert alert-primary">
/* do not edit */                 <h5>Es gibt noch eine zweite Runde mit neuen Zielen!</h5>
/* do not edit */                 <p>Sie beginnt am <b>Samstag, 30. Mai</b>.</p>
/* do not edit */             </div>`,
/* do not edit */             startDate: new Date("2020-04-28"),
/* do not edit */             text: `<p>- Das AG radelt, rollert und läuft gemeinsam einmal um die Welt! -</p><p>Ziel unseres Projekts <b><i>AG</i>tiv</b> ist es, eine Abwechslung zum momentan sehr bewegungsarmen Home School Alltag zu bieten und auch in Zeiten des social distancing den Gemeinschaftsgeist am Allgäu-Gymnasium zu pflegen. </p>
/* do not edit */             <p>Mit einer <b>sportlichen Gemeinschaftsleistung</b> der gesamten Schulfamilie wollen wir versuchen, einmal virtuell die Welt zu umrunden! Aktuell leisten <span class="badge badge-primary fakebadge">{{userCount}} Teilnehmer</span> ihren
/* do not edit */                 Beitrag für dieses Ziel.
/* do not edit */             </p>
/* do not edit */             <p>Jedes Mitglied der Schulfamilie - egal ob Radler, Läufer oder Inliner/Skiroller - kann jeden Tag einen kleinen Beitrag dazu leisten. Näheres erfahrt Ihr in den Regeln. </p>
/* do not edit */             <p>Zum Mitmachen eingeladen sind alle Schülerinnen und Schüler, deren Eltern und sowie alle Lehrkräfte am Allgäu-Gymnasium. Viel Spaß beim Trainieren! </p>
/* do not edit */             <p>Eure Fachschaft Sport</p>`,
/* do not edit */             cities: [
/* do not edit */                 {
/* do not edit */                     name: "Kempten",
/* do not edit */                     country: "de",
/* do not edit */                     distance: 0,
/* do not edit */                     x: 1183,
/* do not edit */                     y: 426,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Marseille",
/* do not edit */                     country: "fr",
/* do not edit */                     distance: 964,
/* do not edit */                     x: 1159,
/* do not edit */                     y: 462,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Barcelona",
/* do not edit */                     country: "es",
/* do not edit */                     distance: 508,
/* do not edit */                     x: 1136,
/* do not edit */                     y: 481,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Gibraltar",
/* do not edit */                     country: "gi",
/* do not edit */                     distance: 1108,
/* do not edit */                     x: 1104,
/* do not edit */                     y: 513,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Marrakesch",
/* do not edit */                     country: "ma",
/* do not edit */                     distance: 653,
/* do not edit */                     x: 1077,
/* do not edit */                     y: 548,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Ad Dakhla",
/* do not edit */                     country: "eh",
/* do not edit */                     distance: 1406,
/* do not edit */                     x: 1034,
/* do not edit */                     y: 585,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Dakar",
/* do not edit */                     country: "sn",
/* do not edit */                     distance: 1367,
/* do not edit */                     x: 1008,
/* do not edit */                     y: 657,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Conakry",
/* do not edit */                     country: "gn",
/* do not edit */                     distance: 1199,
/* do not edit */                     x: 1027,
/* do not edit */                     y: 682,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Makeni",
/* do not edit */                     country: "sl",
/* do not edit */                     distance: 271,
/* do not edit */                     x: 1051,
/* do not edit */                     y: 690,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Nzerekore",
/* do not edit */                     country: "gn",
/* do not edit */                     distance: 516,
/* do not edit */                     x: 1077,
/* do not edit */                     y: 699,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Yamoussoukro",
/* do not edit */                     country: "ci",
/* do not edit */                     distance: 519,
/* do not edit */                     x: 1089,
/* do not edit */                     y: 703,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Kumasi",
/* do not edit */                     country: "gh",
/* do not edit */                     distance: 516,
/* do not edit */                     x: 1118,
/* do not edit */                     y: 706,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Porto-Novo",
/* do not edit */                     country: "bj",
/* do not edit */                     distance: 648,
/* do not edit */                     x: 1139,
/* do not edit */                     y: 708,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Onitsha",
/* do not edit */                     country: "ng",
/* do not edit */                     distance: 543,
/* do not edit */                     x: 1163,
/* do not edit */                     y: 710,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Douala",
/* do not edit */                     country: "cm",
/* do not edit */                     distance: 666,
/* do not edit */                     x: 1180,
/* do not edit */                     y: 723,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Oyem",
/* do not edit */                     country: "ga",
/* do not edit */                     distance: 546,
/* do not edit */                     x: 1195,
/* do not edit */                     y: 740,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Mandilou",
/* do not edit */                     country: "ga",
/* do not edit */                     distance: 602,
/* do not edit */                     x: 1181,
/* do not edit */                     y: 756,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Dolisie",
/* do not edit */                     country: "cg",
/* do not edit */                     distance: 445,
/* do not edit */                     x: 1190,
/* do not edit */                     y: 770,
/* do not edit */                     left: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Kinshasa",
/* do not edit */                     country: "cd",
/* do not edit */                     distance: 390,
/* do not edit */                     x: 1214,
/* do not edit */                     y: 773,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Luanda",
/* do not edit */                     country: "ao",
/* do not edit */                     distance: 818,
/* do not edit */                     x: 1205,
/* do not edit */                     y: 795,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Lubango",
/* do not edit */                     country: "ao",
/* do not edit */                     distance: 898,
/* do not edit */                     x: 1208,
/* do not edit */                     y: 844,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Windhuk",
/* do not edit */                     country: "na",
/* do not edit */                     distance: 1158,
/* do not edit */                     x: 1221,
/* do not edit */                     y: 890,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Kapstadt",
/* do not edit */                     country: "za",
/* do not edit */                     distance: 1479,
/* do not edit */                     x: 1230,
/* do not edit */                     y: 966,
/* do not edit */                     left: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Port Elizabeth",
/* do not edit */                     country: "za",
/* do not edit */                     distance: 749,
/* do not edit */                     x: 1285,
/* do not edit */                     y: 969,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Durban",
/* do not edit */                     country: "za",
/* do not edit */                     distance: 910,
/* do not edit */                     x: 1313,
/* do not edit */                     y: 949,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Maputo",
/* do not edit */                     country: "mz",
/* do not edit */                     distance: 542,
/* do not edit */                     x: 1323,
/* do not edit */                     y: 922,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Harare",
/* do not edit */                     country: "zw",
/* do not edit */                     distance: 1163,
/* do not edit */                     x: 1307,
/* do not edit */                     y: 847,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Lilongwe",
/* do not edit */                     country: "mw",
/* do not edit */                     distance: 817,
/* do not edit */                     x: 1324,
/* do not edit */                     y: 821,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Dodoma",
/* do not edit */                     country: "tz",
/* do not edit */                     distance: 1312,
/* do not edit */                     x: 1345,
/* do not edit */                     y: 778,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Nairobi",
/* do not edit */                     country: "ke",
/* do not edit */                     distance: 689,
/* do not edit */                     x: 1352,
/* do not edit */                     y: 750,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Awassa",
/* do not edit */                     country: "et",
/* do not edit */                     distance: 1273,
/* do not edit */                     x: 1368,
/* do not edit */                     y: 708,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Dschibuti",
/* do not edit */                     country: "dj",
/* do not edit */                     distance: 998,
/* do not edit */                     x: 1389,
/* do not edit */                     y: 676,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Salala",
/* do not edit */                     country: "om",
/* do not edit */                     distance: 1549,
/* do not edit */                     x: 1469,
/* do not edit */                     y: 641,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Dubai",
/* do not edit */                     country: "ae",
/* do not edit */                     distance: 1281,
/* do not edit */                     x: 1480,
/* do not edit */                     y: 590,
/* do not edit */                     left: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Tschahbahar",
/* do not edit */                     country: "ir",
/* do not edit */                     distance: 667,
/* do not edit */                     x: 1516,
/* do not edit */                     y: 587,
/* do not edit */                     angleCCW: false,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Karatschi",
/* do not edit */                     country: "pk",
/* do not edit */                     distance: 980,
/* do not edit */                     x: 1550,
/* do not edit */                     y: 590,
/* do not edit */                     angleCCW: false,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Ahmedabad",
/* do not edit */                     country: "in",
/* do not edit */                     distance: 851,
/* do not edit */                     x: 1588,
/* do not edit */                     y: 602,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Mumbai",
/* do not edit */                     country: "in",
/* do not edit */                     distance: 525,
/* do not edit */                     x: 1592,
/* do not edit */                     y: 628,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Madurai",
/* do not edit */                     country: "in",
/* do not edit */                     distance: 1427,
/* do not edit */                     x: 1626,
/* do not edit */                     y: 686,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Kakinada",
/* do not edit */                     country: "in",
/* do not edit */                     distance: 1123,
/* do not edit */                     x: 1660,
/* do not edit */                     y: 632,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Kalkutta",
/* do not edit */                     country: "in",
/* do not edit */                     distance: 1025,
/* do not edit */                     x: 1688,
/* do not edit */                     y: 607,
/* do not edit */                     angleCCW: false,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Mandalay",
/* do not edit */                     country: "mm",
/* do not edit */                     distance: 1399,
/* do not edit */                     x: 1744,
/* do not edit */                     y: 612,
/* do not edit */                     angleCCW: false,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Rangun",
/* do not edit */                     country: "mm",
/* do not edit */                     distance: 628,
/* do not edit */                     x: 1741,
/* do not edit */                     y: 638,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Bangkok",
/* do not edit */                     country: "th",
/* do not edit */                     distance: 837,
/* do not edit */                     x: 1770,
/* do not edit */                     y: 657,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Phnom Penh",
/* do not edit */                     country: "kh",
/* do not edit */                     distance: 719,
/* do not edit */                     x: 1793,
/* do not edit */                     y: 659,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Pleiku",
/* do not edit */                     country: "vn",
/* do not edit */                     distance: 627,
/* do not edit */                     x: 1816,
/* do not edit */                     y: 659,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Hanoi",
/* do not edit */                     country: "vn",
/* do not edit */                     distance: 1102,
/* do not edit */                     x: 1794,
/* do not edit */                     y: 618,
/* do not edit */                     angleCCW: false,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Hongkong",
/* do not edit */                     country: "hk",
/* do not edit */                     distance: 1078,
/* do not edit */                     x: 1853,
/* do not edit */                     y: 605,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Zhangzhou",
/* do not edit */                     country: "cn",
/* do not edit */                     distance: 713,
/* do not edit */                     x: 1873,
/* do not edit */                     y: 587,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Fuzhou",
/* do not edit */                     country: "cn",
/* do not edit */                     distance: 834,
/* do not edit */                     x: 1853,
/* do not edit */                     y: 562,
/* do not edit */                     angleCCW: false,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Shanghai",
/* do not edit */                     country: "cn",
/* do not edit */                     distance: 771,
/* do not edit */                     x: 1900,
/* do not edit */                     y: 545,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Peking",
/* do not edit */                     country: "cn",
/* do not edit */                     distance: 1191,
/* do not edit */                     x: 1859,
/* do not edit */                     y: 481,
/* do not edit */                     angleCCW: false,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Shengyang",
/* do not edit */                     country: "cn",
/* do not edit */                     distance: 685,
/* do not edit */                     x: 1916,
/* do not edit */                     y: 459,
/* do not edit */                     angleCCW: false,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Wladiwostok",
/* do not edit */                     country: "ru",
/* do not edit */                     distance: 1095,
/* do not edit */                     x: 1967,
/* do not edit */                     y: 456,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Chabarowsk",
/* do not edit */                     country: "ru",
/* do not edit */                     distance: 795,
/* do not edit */                     x: 1984,
/* do not edit */                     y: 412,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Swobodny",
/* do not edit */                     country: "ru",
/* do not edit */                     distance: 764,
/* do not edit */                     x: 1941,
/* do not edit */                     y: 385,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Nerjungri",
/* do not edit */                     country: "ru",
/* do not edit */                     distance: 851,
/* do not edit */                     x: 1913,
/* do not edit */                     y: 340,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Jakutsk",
/* do not edit */                     country: "ru",
/* do not edit */                     distance: 861,
/* do not edit */                     x: 1951,
/* do not edit */                     y: 293,
/* do not edit */                     angleCCW: false,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Sussuman",
/* do not edit */                     country: "ru",
/* do not edit */                     distance: 1228,
/* do not edit */                     x: 2071,
/* do not edit */                     y: 285,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Magadan",
/* do not edit */                     country: "ru",
/* do not edit */                     distance: 626,
/* do not edit */                     x: 2089,
/* do not edit */                     y: 317,
/* do not edit */                     angleCCW: true,
/* do not edit */                     isEasternEndpoint: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Anchorage",
/* do not edit */                     country: "us",
/* do not edit */                     distance: 2832,
/* do not edit */                     x: 95,
/* do not edit */                     y: 346,
/* do not edit */                     isWesternStartpoint: true,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Watson Lake",
/* do not edit */                     country: "ca",
/* do not edit */                     distance: 1569,
/* do not edit */                     x: 272,
/* do not edit */                     y: 352,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Prince George",
/* do not edit */                     country: "ca",
/* do not edit */                     distance: 1323,
/* do not edit */                     x: 327,
/* do not edit */                     y: 391,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Vancouver",
/* do not edit */                     country: "ca",
/* do not edit */                     distance: 783,
/* do not edit */                     x: 339,
/* do not edit */                     y: 427,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Portland",
/* do not edit */                     country: "us",
/* do not edit */                     distance: 509,
/* do not edit */                     x: 339,
/* do not edit */                     y: 459,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Sacramento",
/* do not edit */                     country: "us",
/* do not edit */                     distance: 930,
/* do not edit */                     x: 346,
/* do not edit */                     y: 512,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Los Angeles",
/* do not edit */                     country: "us",
/* do not edit */                     distance: 617,
/* do not edit */                     x: 369,
/* do not edit */                     y: 543,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Phoenix",
/* do not edit */                     country: "us",
/* do not edit */                     distance: 600,
/* do not edit */                     x: 413,
/* do not edit */                     y: 548,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Hermosillo",
/* do not edit */                     country: "mx",
/* do not edit */                     distance: 861,
/* do not edit */                     x: 423,
/* do not edit */                     y: 569,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Guadalajara",
/* do not edit */                     country: "mx",
/* do not edit */                     distance: 1355,
/* do not edit */                     x: 461,
/* do not edit */                     y: 621,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Mexiko Stadt",
/* do not edit */                     country: "mx",
/* do not edit */                     distance: 553,
/* do not edit */                     x: 484,
/* do not edit */                     y: 635,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Oaxaca",
/* do not edit */                     country: "mx",
/* do not edit */                     distance: 462,
/* do not edit */                     x: 500,
/* do not edit */                     y: 648,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Guatemala Stadt",
/* do not edit */                     country: "gt",
/* do not edit */                     distance: 986,
/* do not edit */                     x: 535,
/* do not edit */                     y: 660,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Tegucigalpa",
/* do not edit */                     country: "hn",
/* do not edit */                     distance: 651,
/* do not edit */                     x: 559,
/* do not edit */                     y: 668,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Managua",
/* do not edit */                     country: "ni",
/* do not edit */                     distance: 366,
/* do not edit */                     x: 568,
/* do not edit */                     y: 678,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "San José",
/* do not edit */                     country: "cr",
/* do not edit */                     distance: 424,
/* do not edit */                     x: 578,
/* do not edit */                     y: 693,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Panama City",
/* do not edit */                     country: "pa",
/* do not edit */                     distance: 851,
/* do not edit */                     x: 609,
/* do not edit */                     y: 703,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Medellin",
/* do not edit */                     country: "co",
/* do not edit */                     distance: 494,
/* do not edit */                     x: 637,
/* do not edit */                     y: 718,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Quito",
/* do not edit */                     country: "ec",
/* do not edit */                     distance: 1183,
/* do not edit */                     x: 614,
/* do not edit */                     y: 757,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Guayaquil",
/* do not edit */                     country: "ec",
/* do not edit */                     distance: 421,
/* do not edit */                     x: 607,
/* do not edit */                     y: 769,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Sullana",
/* do not edit */                     country: "pe",
/* do not edit */                     distance: 451,
/* do not edit */                     x: 600,
/* do not edit */                     y: 785,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Lima",
/* do not edit */                     country: "pe",
/* do not edit */                     distance: 1019,
/* do not edit */                     x: 623,
/* do not edit */                     y: 827,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "La Paz",
/* do not edit */                     country: "bo",
/* do not edit */                     distance: 1517,
/* do not edit */                     x: 675,
/* do not edit */                     y: 853,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Antofagasta",
/* do not edit */                     country: "cl",
/* do not edit */                     distance: 1116,
/* do not edit */                     x: 670,
/* do not edit */                     y: 893,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Santiago de Chile",
/* do not edit */                     country: "cl",
/* do not edit */                     distance: 1335,
/* do not edit */                     x: 664,
/* do not edit */                     y: 968,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Bariloche",
/* do not edit */                     country: "ar",
/* do not edit */                     distance: 1155,
/* do not edit */                     x: 653,
/* do not edit */                     y: 1021,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Rio Gallegos",
/* do not edit */                     country: "ar",
/* do not edit */                     distance: 1539,
/* do not edit */                     x: 680,
/* do not edit */                     y: 1099,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Comodo Rivadavia",
/* do not edit */                     country: "ar",
/* do not edit */                     distance: 779,
/* do not edit */                     x: 692,
/* do not edit */                     y: 1058,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Bahia Blanca",
/* do not edit */                     country: "ar",
/* do not edit */                     distance: 1093,
/* do not edit */                     x: 729,
/* do not edit */                     y: 1011,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Buenos Aires",
/* do not edit */                     country: "ar",
/* do not edit */                     distance: 635,
/* do not edit */                     x: 752,
/* do not edit */                     y: 987,
/* do not edit */                     left: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Montevideo",
/* do not edit */                     country: "uy",
/* do not edit */                     distance: 184,
/* do not edit */                     x: 764,
/* do not edit */                     y: 982,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Porto Alegre",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 789,
/* do not edit */                     x: 797,
/* do not edit */                     y: 941,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Curtiba",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 684,
/* do not edit */                     x: 809,
/* do not edit */                     y: 916,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Sao Paulo",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 417,
/* do not edit */                     x: 833,
/* do not edit */                     y: 902,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Rio de Janeiro",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 434,
/* do not edit */                     x: 855,
/* do not edit */                     y: 892,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Vitória",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 524,
/* do not edit */                     x: 867,
/* do not edit */                     y: 869,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Salvador",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 1167,
/* do not edit */                     x: 870,
/* do not edit */                     y: 827,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Recife",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 805,
/* do not edit */                     x: 896,
/* do not edit */                     y: 801,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Fortaleza",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 759,
/* do not edit */                     x: 868,
/* do not edit */                     y: 772,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Sao Luis",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 900,
/* do not edit */                     x: 831,
/* do not edit */                     y: 772,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Belèm",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 580,
/* do not edit */                     x: 806,
/* do not edit */                     y: 758,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Macapá",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 333,
/* do not edit */                     x: 794,
/* do not edit */                     y: 746,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Cayenne",
/* do not edit */                     country: "gf",
/* do not edit */                     distance: 333,
/* do not edit */                     x: 781,
/* do not edit */                     y: 720,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Paramaribo",
/* do not edit */                     country: "sr",
/* do not edit */                     distance: 333,
/* do not edit */                     x: 762,
/* do not edit */                     y: 711,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Georgetown",
/* do not edit */                     country: "gy",
/* do not edit */                     distance: 444,
/* do not edit */                     x: 737,
/* do not edit */                     y: 706,
/* do not edit */                     angleCCW: false,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Caracas",
/* do not edit */                     country: "ve",
/* do not edit */                     distance: 1044,
/* do not edit */                     x: 681,
/* do not edit */                     y: 688,
/* do not edit */                     left: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Port au Prince",
/* do not edit */                     country: "ht",
/* do not edit */                     distance: 520,
/* do not edit */                     x: 662,
/* do not edit */                     y: 643,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Havanna",
/* do not edit */                     country: "cu",
/* do not edit */                     distance: 880,
/* do not edit */                     x: 596,
/* do not edit */                     y: 609,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Miami",
/* do not edit */                     country: "us",
/* do not edit */                     distance: 1068,
/* do not edit */                     x: 602,
/* do not edit */                     y: 585,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Atlanta",
/* do not edit */                     country: "us",
/* do not edit */                     distance: 711,
/* do not edit */                     x: 573,
/* do not edit */                     y: 538,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Charlotte",
/* do not edit */                     country: "us",
/* do not edit */                     distance: 268,
/* do not edit */                     x: 600,
/* do not edit */                     y: 520,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Washington",
/* do not edit */                     country: "us",
/* do not edit */                     distance: 405,
/* do not edit */                     x: 628,
/* do not edit */                     y: 487,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "New York City",
/* do not edit */                     country: "us",
/* do not edit */                     distance: 241,
/* do not edit */                     x: 653,
/* do not edit */                     y: 477,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Bangor",
/* do not edit */                     country: "us",
/* do not edit */                     distance: 481,
/* do not edit */                     x: 671,
/* do not edit */                     y: 451,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Rigolet",
/* do not edit */                     country: "ca",
/* do not edit */                     distance: 1280,
/* do not edit */                     x: 736,
/* do not edit */                     y: 373,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Nanortalik",
/* do not edit */                     country: "gl",
/* do not edit */                     distance: 1028,
/* do not edit */                     x: 807,
/* do not edit */                     y: 319,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Ammassalik",
/* do not edit */                     country: "gl",
/* do not edit */                     distance: 720,
/* do not edit */                     x: 876,
/* do not edit */                     y: 270,
/* do not edit */                     angleCCW: false,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Reykjavík",
/* do not edit */                     country: "is",
/* do not edit */                     distance: 757,
/* do not edit */                     x: 963,
/* do not edit */                     y: 282,
/* do not edit */                     angleCCW: false,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Neskaupstaður",
/* do not edit */                     country: "is",
/* do not edit */                     distance: 703,
/* do not edit */                     x: 1024,
/* do not edit */                     y: 271,
/* do not edit */                     angleCCW: false,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Bodø",
/* do not edit */                     country: "no",
/* do not edit */                     distance: 1269,
/* do not edit */                     x: 1213,
/* do not edit */                     y: 255,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Nordkap",
/* do not edit */                     country: "no",
/* do not edit */                     distance: 995,
/* do not edit */                     x: 1287,
/* do not edit */                     y: 212,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Murmansk",
/* do not edit */                     country: "ru",
/* do not edit */                     distance: 709,
/* do not edit */                     x: 1337,
/* do not edit */                     y: 240,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Oulu",
/* do not edit */                     country: "fi",
/* do not edit */                     distance: 1473,
/* do not edit */                     x: 1286,
/* do not edit */                     y: 277,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Petrosawodsk",
/* do not edit */                     country: "ru",
/* do not edit */                     distance: 758,
/* do not edit */                     x: 1349,
/* do not edit */                     y: 314,
/* do not edit */                     left: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Archangelsk",
/* do not edit */                     country: "ru",
/* do not edit */                     distance: 1335,
/* do not edit */                     x: 1386,
/* do not edit */                     y: 279,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Kotlas",
/* do not edit */                     country: "ru",
/* do not edit */                     distance: 631,
/* do not edit */                     x: 1414,
/* do not edit */                     y: 314,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Perm",
/* do not edit */                     country: "ru",
/* do not edit */                     distance: 923,
/* do not edit */                     x: 1477,
/* do not edit */                     y: 340,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Kasan",
/* do not edit */                     country: "ru",
/* do not edit */                     distance: 663,
/* do not edit */                     x: 1432,
/* do not edit */                     y: 357,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Moskau",
/* do not edit */                     country: "ru",
/* do not edit */                     distance: 810,
/* do not edit */                     x: 1369,
/* do not edit */                     y: 358,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Minsk",
/* do not edit */                     country: "by",
/* do not edit */                     distance: 715,
/* do not edit */                     x: 1298,
/* do not edit */                     y: 374,
/* do not edit */                     angleCCW: true,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Danzig",
/* do not edit */                     country: "pl",
/* do not edit */                     distance: 715,
/* do not edit */                     x: 1242,
/* do not edit */                     y: 372,
/* do not edit */                     angleCCW: false,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Kopenhagen",
/* do not edit */                     country: "dk",
/* do not edit */                     distance: 609,
/* do not edit */                     x: 1198,
/* do not edit */                     y: 357,
/* do not edit */                     angleCCW: false,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Hamburg",
/* do not edit */                     country: "de",
/* do not edit */                     distance: 338,
/* do not edit */                     x: 1188,
/* do not edit */                     y: 384,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Würzburg",
/* do not edit */                     country: "de",
/* do not edit */                     distance: 518,
/* do not edit */                     x: 1189,
/* do not edit */                     y: 409,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Kempten",
/* do not edit */                     country: "de",
/* do not edit */                     distance: 268,
/* do not edit */                     x: 1183,
/* do not edit */                     y: 426,
/* do not edit */                     image: "de_kempten_2.jpg",
/* do not edit */                 },
/* do not edit */             ],
/* do not edit */         },
/* do not edit */         {
/* do not edit */             id: 2,
/* do not edit */             postText: `PLATZHALTER POSTTEXT RUNDE 2`,
/* do not edit */             text: `<p>- Das AG radelt, rollert, läuft, schwimmt und klettert auf einer <span class="badge badge-primary big-badge">zweiten Runde</span> mit einer brandneuen Route erneut gemeinsam  um die Welt! -</p><p>Ziel unseres Projekts <b><i>AG</i>tiv</b> bleibt es weiterhin, eine Abwechslung zum immer noch bewegungsarmen Home School Alltag zu bieten und auch in Zeiten des social distancing den Gemeinschaftsgeist am Allgäu-Gymnasium zu pflegen. </p>
/* do not edit */             <p>Mit einer <b>sportlichen Gemeinschaftsleistung</b> der gesamten Schulfamilie wollen wir erneut versuchen, auf einer neuen Strecke virtuell die Welt zu bereisen und dabei neue Orte zu entdecken! Die <b>Teilnehmeraccounts bleiben bestehen</b>, jedoch wird der <b>Kilometerstand der ersten Runde zurückgesetzt</b>. Ihr könnt aber trotzdem eure in der 1. Runde erzielte Leistungen unter dem Tab "Runde 1" bei "Meine Strecken" ansehen. Wir starten also alle bei 0 km!</p><p>Lasst uns die 2. Runde beginnen! Aktuell leisten <span class="badge badge-primary fakebadge">{{userCount}} Teilnehmer</span> ihren Beitrag für dieses Ziel.
/* do not edit */             </p>
/* do not edit */             <p>Jedes Mitglied der Schulfamilie - egal ob Radler, Läufer, Inliner/Skiroller, Schwimmer oder Kletterer - kann jeden Tag einen kleinen Beitrag dazu leisten. Näheres erfahrt Ihr in den Regeln.</p>
/* do not edit */             <p>Zum Mitmachen eingeladen sind alle Schülerinnen und Schüler, deren Eltern und sowie alle Lehrkräfte am Allgäu-Gymnasium. Viel Spaß beim Trainieren! </p>
/* do not edit */             <p>Eure Fachschaft Sport</p>`,
/* do not edit */             startDate: new Date("2020-05-30"),
/* do not edit */             cities: [
/* do not edit */                 {
/* do not edit */                     name: "Kempten",
/* do not edit */                     country: "de",
/* do not edit */                     distance: 0,
/* do not edit */                     x: 1183,
/* do not edit */                     y: 426,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Zagreb",
/* do not edit */                     country: "hr",
/* do not edit */                     distance: 673,
/* do not edit */                     x: 1226,
/* do not edit */                     y: 442,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Belgrad",
/* do not edit */                     country: "rs",
/* do not edit */                     distance: 393,
/* do not edit */                     x: 1259,
/* do not edit */                     y: 452,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Sofia",
/* do not edit */                     country: "bg",
/* do not edit */                     distance: 392,
/* do not edit */                     x: 1274,
/* do not edit */                     y: 464,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Istanbul",
/* do not edit */                     country: "tr",
/* do not edit */                     distance: 550,
/* do not edit */                     x: 1302,
/* do not edit */                     y: 480,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Samsun",
/* do not edit */                     country: "tr",
/* do not edit */                     distance: 744,
/* do not edit */                     x: 1351,
/* do not edit */                     y: 478,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Tiflis",
/* do not edit */                     country: "ge",
/* do not edit */                     distance: 901,
/* do not edit */                     x: 1414,
/* do not edit */                     y: 473,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Baku",
/* do not edit */                     country: "az",
/* do not edit */                     distance: 580,
/* do not edit */                     x: 1436,
/* do not edit */                     y: 497,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Teheran",
/* do not edit */                     country: "ir",
/* do not edit */                     distance: 785,
/* do not edit */                     x: 1458,
/* do not edit */                     y: 520,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Aşgabat",
/* do not edit */                     country: "tm",
/* do not edit */                     distance: 956,
/* do not edit */                     x: 1493,
/* do not edit */                     y: 497,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Herat",
/* do not edit */                     country: "af",
/* do not edit */                     distance: 696,
/* do not edit */                     x: 1514,
/* do not edit */                     y: 526,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Kabul",
/* do not edit */                     country: "af",
/* do not edit */                     distance: 817,
/* do not edit */                     x: 1566,
/* do not edit */                     y: 525,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Islamabad",
/* do not edit */                     country: "pk",
/* do not edit */                     distance: 472,
/* do not edit */                     x: 1589,
/* do not edit */                     y: 535,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Lahore",
/* do not edit */                     country: "pk",
/* do not edit */                     distance: 374,
/* do not edit */                     x: 1602,
/* do not edit */                     y: 553,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Neu-Delhi",
/* do not edit */                     country: "in",
/* do not edit */                     distance: 512,
/* do not edit */                     x: 1621,
/* do not edit */                     y: 568,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Ghorahi",
/* do not edit */                     country: "np",
/* do not edit */                     distance: 980,
/* do not edit */                     x: 1647,
/* do not edit */                     y: 575,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Kathmandu",
/* do not edit */                     country: "np",
/* do not edit */                     distance: 420,
/* do not edit */                     x: 1670,
/* do not edit */                     y: 577,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Khumjung",
/* do not edit */                     country: "np",
/* do not edit */                     distance: 350,
/* do not edit */                     x: 1682,
/* do not edit */                     y: 568,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Thimphu",
/* do not edit */                     country: "bt",
/* do not edit */                     distance: 819,
/* do not edit */                     x: 1701,
/* do not edit */                     y: 574,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Lhasa",
/* do not edit */                     country: "cn",
/* do not edit */                     distance: 986,
/* do not edit */                     x: 1709,
/* do not edit */                     y: 550,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Qamdo",
/* do not edit */                     country: "cn",
/* do not edit */                     distance: 1097,
/* do not edit */                     x: 1739,
/* do not edit */                     y: 538,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Xining",
/* do not edit */                     country: "cn",
/* do not edit */                     distance: 1113,
/* do not edit */                     x: 1768,
/* do not edit */                     y: 509,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Xi’an",
/* do not edit */                     country: "cn",
/* do not edit */                     distance: 845,
/* do not edit */                     x: 1809,
/* do not edit */                     y: 519,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Shijiazhuang",
/* do not edit */                     country: "cn",
/* do not edit */                     distance: 813,
/* do not edit */                     x: 1853,
/* do not edit */                     y: 497,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Yantai",
/* do not edit */                     country: "cn",
/* do not edit */                     distance: 738,
/* do not edit */                     x: 1900,
/* do not edit */                     y: 501,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Seoul",
/* do not edit */                     country: "kr",
/* do not edit */                     distance: 488,
/* do not edit */                     x: 1934,
/* do not edit */                     y: 500,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Busan",
/* do not edit */                     country: "kr",
/* do not edit */                     distance: 326,
/* do not edit */                     x: 1950,
/* do not edit */                     y: 514,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Kumamoto",
/* do not edit */                     country: "jp",
/* do not edit */                     distance: 304,
/* do not edit */                     x: 1964,
/* do not edit */                     y: 543,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Nago",
/* do not edit */                     country: "jp",
/* do not edit */                     distance: 875,
/* do not edit */                     x: 1948,
/* do not edit */                     y: 576,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Taipeh",
/* do not edit */                     country: "tw",
/* do not edit */                     distance: 665,
/* do not edit */                     x: 1902,
/* do not edit */                     y: 588,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Tuguegarao City",
/* do not edit */                     country: "ph",
/* do not edit */                     distance: 828,
/* do not edit */                     x: 1907,
/* do not edit */                     y: 640,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Manila",
/* do not edit */                     country: "ph",
/* do not edit */                     distance: 478,
/* do not edit */                     x: 1898,
/* do not edit */                     y: 656,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Tacloban City",
/* do not edit */                     country: "ph",
/* do not edit */                     distance: 859,
/* do not edit */                     x: 1911,
/* do not edit */                     y: 673,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Davao City",
/* do not edit */                     country: "ph",
/* do not edit */                     distance: 644,
/* do not edit */                     x: 1920,
/* do not edit */                     y: 693,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Bandar Seri Begawan",
/* do not edit */                     country: "bn",
/* do not edit */                     distance: 1223,
/* do not edit */                     x: 1867,
/* do not edit */                     y: 708,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Pontianak",
/* do not edit */                     country: "id",
/* do not edit */                     distance: 1208,
/* do not edit */                     x: 1824,
/* do not edit */                     y: 751,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Jakarta",
/* do not edit */                     country: "id",
/* do not edit */                     distance: 738,
/* do not edit */                     x: 1815,
/* do not edit */                     y: 788,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Surabaya",
/* do not edit */                     country: "id",
/* do not edit */                     distance: 661,
/* do not edit */                     x: 1874,
/* do not edit */                     y: 798,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Labuhanbajo",
/* do not edit */                     country: "id",
/* do not edit */                     distance: 802,
/* do not edit */                     x: 1902,
/* do not edit */                     y: 811,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Dili",
/* do not edit */                     country: "tl",
/* do not edit */                     distance: 611,
/* do not edit */                     x: 1936,
/* do not edit */                     y: 808,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Darwin",
/* do not edit */                     country: "au",
/* do not edit */                     distance: 729,
/* do not edit */                     x: 1967,
/* do not edit */                     y: 833,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Daly Waters",
/* do not edit */                     country: "au",
/* do not edit */                     distance: 590,
/* do not edit */                     x: 1992,
/* do not edit */                     y: 861,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Alice Springs",
/* do not edit */                     country: "au",
/* do not edit */                     distance: 915,
/* do not edit */                     x: 1998,
/* do not edit */                     y: 901,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Mutitjulu",
/* do not edit */                     country: "au",
/* do not edit */                     distance: 470,
/* do not edit */                     x: 1977,
/* do not edit */                     y: 910,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Coober Pedy",
/* do not edit */                     country: "au",
/* do not edit */                     distance: 661,
/* do not edit */                     x: 1994,
/* do not edit */                     y: 935,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Adelaide",
/* do not edit */                     country: "au",
/* do not edit */                     distance: 759,
/* do not edit */                     x: 2018,
/* do not edit */                     y: 979,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Melbourne",
/* do not edit */                     country: "au",
/* do not edit */                     distance: 727,
/* do not edit */                     x: 2054,
/* do not edit */                     y: 1004,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Sydney",
/* do not edit */                     country: "au",
/* do not edit */                     distance: 878,
/* do not edit */                     x: 2098,
/* do not edit */                     y: 976,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Auckland",
/* do not edit */                     country: "nz",
/* do not edit */                     distance: 2145,
/* do not edit */                     x: 2249,
/* do not edit */                     y: 989,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Suva",
/* do not edit */                     country: "fj",
/* do not edit */                     distance: 2112,
/* do not edit */                     x: 2256,
/* do not edit */                     y: 870,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Nuku'alofa",
/* do not edit */                     country: "to",
/* do not edit */                     distance: 987,
/* do not edit */                     x: 2288,
/* do not edit */                     y: 882,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Apia",
/* do not edit */                     country: "ws",
/* do not edit */                     distance: 898,
/* do not edit */                     x: 2301,
/* do not edit */                     y: 861,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Avarua",
/* do not edit */                     country: "ck",
/* do not edit */                     distance: 1512,
/* do not edit */                     x: 2334,
/* do not edit */                     y: 883,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Papeete",
/* do not edit */                     country: "pf",
/* do not edit */                     distance: 1147,
/* do not edit */                     x: 96,
/* do not edit */                     y: 838,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Adamstown",
/* do not edit */                     country: "pn",
/* do not edit */                     distance: 2183,
/* do not edit */                     x: 282,
/* do not edit */                     y: 920,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Osterinsel",
/* do not edit */                     country: "cl",
/* do not edit */                     distance: 2068,
/* do not edit */                     x: 429,
/* do not edit */                     y: 940,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Robinson Crusoe Insel",
/* do not edit */                     country: "cl",
/* do not edit */                     distance: 3015,
/* do not edit */                     x: 601,
/* do not edit */                     y: 966,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Santiago de Chile",
/* do not edit */                     country: "cl",
/* do not edit */                     distance: 760,
/* do not edit */                     x: 664,
/* do not edit */                     y: 968,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Córdoba",
/* do not edit */                     country: "ar",
/* do not edit */                     distance: 646,
/* do not edit */                     x: 712,
/* do not edit */                     y: 955,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Asunción",
/* do not edit */                     country: "py",
/* do not edit */                     distance: 1200,
/* do not edit */                     x: 754,
/* do not edit */                     y: 908,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Campo Grande",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 752,
/* do not edit */                     x: 769,
/* do not edit */                     y: 884,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Cuiabá",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 704,
/* do not edit */                     x: 758,
/* do not edit */                     y: 857,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Ji-Paraná",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 1085,
/* do not edit */                     x: 738,
/* do not edit */                     y: 829,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Porto Velho",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 377,
/* do not edit */                     x: 718,
/* do not edit */                     y: 811,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Manaus",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 888,
/* do not edit */                     x: 736,
/* do not edit */                     y: 782,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Santarém",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 610,
/* do not edit */                     x: 769,
/* do not edit */                     y: 768,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Macapá",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 550,
/* do not edit */                     x: 794,
/* do not edit */                     y: 746,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "São Luís",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 840,
/* do not edit */                     x: 831,
/* do not edit */                     y: 772,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Natal",
/* do not edit */                     country: "br",
/* do not edit */                     distance: 1423,
/* do not edit */                     x: 928,
/* do not edit */                     y: 789,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Georgetown",
/* do not edit */                     country: "sh",
/* do not edit */                     distance: 3424,
/* do not edit */                     x: 1025,
/* do not edit */                     y: 805,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Benguela",
/* do not edit */                     country: "ao",
/* do not edit */                     distance: 642,
/* do not edit */                     x: 1203,
/* do not edit */                     y: 831,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Dundo",
/* do not edit */                     country: "ao",
/* do not edit */                     distance: 742,
/* do not edit */                     x: 1252,
/* do not edit */                     y: 801,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Mbuji-Mayi",
/* do not edit */                     country: "cd",
/* do not edit */                     distance: 575,
/* do not edit */                     x: 1272,
/* do not edit */                     y: 792,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Kisangani",
/* do not edit */                     country: "cd",
/* do not edit */                     distance: 1357,
/* do not edit */                     x: 1277,
/* do not edit */                     y: 740,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Juba",
/* do not edit */                     country: "ss",
/* do not edit */                     distance: 1354,
/* do not edit */                     x: 1315,
/* do not edit */                     y: 717,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Wau",
/* do not edit */                     country: "ss",
/* do not edit */                     distance: 645,
/* do not edit */                     x: 1276,
/* do not edit */                     y: 701,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "N'Djamena",
/* do not edit */                     country: "td",
/* do not edit */                     distance: 2199,
/* do not edit */                     x: 1218,
/* do not edit */                     y: 676,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Faya-Largeau",
/* do not edit */                     country: "td",
/* do not edit */                     distance: 778,
/* do not edit */                     x: 1253,
/* do not edit */                     y: 635,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Plateau von Djado",
/* do not edit */                     country: "ne",
/* do not edit */                     distance: 794,
/* do not edit */                     x: 1212,
/* do not edit */                     y: 616,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Tamanrasset",
/* do not edit */                     country: "dz",
/* do not edit */                     distance: 727,
/* do not edit */                     x: 1162,
/* do not edit */                     y: 594,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "In Salah",
/* do not edit */                     country: "dz",
/* do not edit */                     distance: 664,
/* do not edit */                     x: 1144,
/* do not edit */                     y: 571,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Touggourt",
/* do not edit */                     country: "dz",
/* do not edit */                     distance: 962,
/* do not edit */                     x: 1171,
/* do not edit */                     y: 541,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Gafsa",
/* do not edit */                     country: "tn",
/* do not edit */                     distance: 336,
/* do not edit */                     x: 1188,
/* do not edit */                     y: 529,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "El Kef",
/* do not edit */                     country: "tn",
/* do not edit */                     distance: 234,
/* do not edit */                     x: 1180,
/* do not edit */                     y: 518,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Tunis",
/* do not edit */                     country: "tn",
/* do not edit */                     distance: 168,
/* do not edit */                     x: 1198,
/* do not edit */                     y: 513,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Marsala",
/* do not edit */                     country: "it",
/* do not edit */                     distance: 285,
/* do not edit */                     x: 1205,
/* do not edit */                     y: 500,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Reggio Calabria",
/* do not edit */                     country: "it",
/* do not edit */                     distance: 371,
/* do not edit */                     x: 1226,
/* do not edit */                     y: 504,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Bari",
/* do not edit */                     country: "it",
/* do not edit */                     distance: 443,
/* do not edit */                     x: 1225,
/* do not edit */                     y: 476,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Rom",
/* do not edit */                     country: "it",
/* do not edit */                     distance: 428,
/* do not edit */                     x: 1202,
/* do not edit */                     y: 475,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Florenz",
/* do not edit */                     country: "it",
/* do not edit */                     distance: 280,
/* do not edit */                     x: 1195,
/* do not edit */                     y: 461,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Mailand",
/* do not edit */                     country: "it",
/* do not edit */                     distance: 305,
/* do not edit */                     x: 1178,
/* do not edit */                     y: 447,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Luzern",
/* do not edit */                     country: "ch",
/* do not edit */                     distance: 243,
/* do not edit */                     x: 1166,
/* do not edit */                     y: 439,
/* do not edit */                 },
/* do not edit */                 {
/* do not edit */                     name: "Kempten",
/* do not edit */                     country: "de",
/* do not edit */                     distance: 295,
/* do not edit */                     x: 1183,
/* do not edit */                     y: 426,
/* do not edit */                     image: "de_kempten_2.jpg",
/* do not edit */                 },
/* do not edit */             ]
/* do not edit */         }
/* do not edit */     ]
/* do not edit */
/* do not edit */     export const countries: Country[] = [
/* do not edit */         {
/* do not edit */             code: "ae",
/* do not edit */             name: "Ver. arab. Emirate"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "af",
/* do not edit */             name: "Afghanistan"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ao",
/* do not edit */             name: "Angola"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ar",
/* do not edit */             name: "Argentinien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "au",
/* do not edit */             name: "Australien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "az",
/* do not edit */             name: "Aserbaidschan"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "bg",
/* do not edit */             name: "Bulgarien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "bj",
/* do not edit */             name: "Benin"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "bn",
/* do not edit */             name: "Brunei"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "bo",
/* do not edit */             name: "Bolivien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "br",
/* do not edit */             name: "Brasilien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "bt",
/* do not edit */             name: "Bhutan"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "by",
/* do not edit */             name: "Weißrussland"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ca",
/* do not edit */             name: "Kanada"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cd",
/* do not edit */             name: "D. R. Kongo"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cd",
/* do not edit */             name: "Demokratische Republik Kongo"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cg",
/* do not edit */             name: "Kongo"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ch",
/* do not edit */             name: "Schweiz"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ci",
/* do not edit */             name: "Cote d`Ivoir"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ck",
/* do not edit */             name: "Cookinseln"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cl",
/* do not edit */             name: "Chile"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cm",
/* do not edit */             name: "Kamerun"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cn",
/* do not edit */             name: "China"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cn",
/* do not edit */             name: "Tibet"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "co",
/* do not edit */             name: "Kolumbien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cr",
/* do not edit */             name: "Costa Rica"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cu",
/* do not edit */             name: "Kuba"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "de",
/* do not edit */             name: "Deutschland"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "dj",
/* do not edit */             name: "Dschibouti"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "dk",
/* do not edit */             name: "Dänemark"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "dz",
/* do not edit */             name: "Algerien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ec",
/* do not edit */             name: "Ecuador"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "eh",
/* do not edit */             name: "Westsahara"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "es",
/* do not edit */             name: "Spanien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "et",
/* do not edit */             name: "Äthiopien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "fi",
/* do not edit */             name: "Finnland"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "fj",
/* do not edit */             name: "Fidschi"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "fr",
/* do not edit */             name: "Frankreich"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ga",
/* do not edit */             name: "Gabun"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ge",
/* do not edit */             name: "Georgien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gf",
/* do not edit */             name: "Franz. Guyana"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gh",
/* do not edit */             name: "Ghana"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gi",
/* do not edit */             name: "Gibraltar"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gl",
/* do not edit */             name: "Grönland"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gn",
/* do not edit */             name: "Guinea"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gt",
/* do not edit */             name: "Guatemala"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gy",
/* do not edit */             name: "Guyana"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "hk",
/* do not edit */             name: "Hongkong"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "hn",
/* do not edit */             name: "Honduras"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "hr",
/* do not edit */             name: "Kroatien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ht",
/* do not edit */             name: "Haiti"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "id",
/* do not edit */             name: "Indonesien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "in",
/* do not edit */             name: "Indien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ir",
/* do not edit */             name: "Iran"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "is",
/* do not edit */             name: "Island"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "it",
/* do not edit */             name: "Italien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "jp",
/* do not edit */             name: "Japan"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ke",
/* do not edit */             name: "Kenia"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "kh",
/* do not edit */             name: "Kambodscha"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "kr",
/* do not edit */             name: "Südkorea"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ma",
/* do not edit */             name: "Marokko"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "mm",
/* do not edit */             name: "Myanmar"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "mw",
/* do not edit */             name: "Malawi"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "mx",
/* do not edit */             name: "Mexiko"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "mz",
/* do not edit */             name: "Mosambik"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "na",
/* do not edit */             name: "Namibia"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ne",
/* do not edit */             name: "Niger"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ng",
/* do not edit */             name: "Nigeria"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ni",
/* do not edit */             name: "Nicaragua"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "no",
/* do not edit */             name: "Norwegen"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "np",
/* do not edit */             name: "Nepal"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "nz",
/* do not edit */             name: "Neuseeland"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "om",
/* do not edit */             name: "Oman"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "pa",
/* do not edit */             name: "Panama"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "pe",
/* do not edit */             name: "Peru"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "pf",
/* do not edit */             name: "Französisch-Polynesien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ph",
/* do not edit */             name: "Philippinen"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "pk",
/* do not edit */             name: "Pakistan"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "pl",
/* do not edit */             name: "Polen"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "pn",
/* do not edit */             name: "Piticairninseln"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "py",
/* do not edit */             name: "Paraguay"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "rs",
/* do not edit */             name: "Serbien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ru",
/* do not edit */             name: "Russland"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "se",
/* do not edit */             name: "Schweden"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "sh",
/* do not edit */             name: "St. Helena"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "sl",
/* do not edit */             name: "Sierra Leone"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "sn",
/* do not edit */             name: "Senegal"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "sr",
/* do not edit */             name: "Suriname"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ss",
/* do not edit */             name: "Südsudan"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "td",
/* do not edit */             name: "Tschad"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "th",
/* do not edit */             name: "Thailand"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "tl",
/* do not edit */             name: "Osttimor"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "tm",
/* do not edit */             name: "Turkmenistan"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "tn",
/* do not edit */             name: "Tunesien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "to",
/* do not edit */             name: "Tonga"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "tr",
/* do not edit */             name: "Türkei"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "tw",
/* do not edit */             name: "Taiwan"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "tz",
/* do not edit */             name: "Tansania"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "us",
/* do not edit */             name: "USA"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "uy",
/* do not edit */             name: "Uruguay"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ve",
/* do not edit */             name: "Venezuela"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "vn",
/* do not edit */             name: "Vietnam"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ws",
/* do not edit */             name: "Samoa"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "za",
/* do not edit */             name: "Südafrika"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "zw",
/* do not edit */             name: "Simbabwe"
/* do not edit */         },
/* do not edit */     ];
/* do not edit */ }
