
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ // tslint:disable-next-line
/* do not edit */ export module data {
/* do not edit */     export interface City {
/* do not edit */         name: string;
/* do not edit */         country: string;
/* do not edit */         distance: number;
/* do not edit */         x: number;
/* do not edit */         y: number;
/* do not edit */         angleCCW?: boolean;
/* do not edit */         left?: boolean;
/* do not edit */         isEasternEndpoint?: boolean;
/* do not edit */         isWesternStartpoint?: boolean;
/* do not edit */         image?: string;
/* do not edit */     }
/* do not edit */
/* do not edit */     export interface Country {
/* do not edit */         code: string;
/* do not edit */         name: string;
/* do not edit */     }
/* do not edit */
/* do not edit */     export const cities: City[] = [
/* do not edit */         {
/* do not edit */             name: "Kempten",
/* do not edit */             country: "de",
/* do not edit */             distance: 0,
/* do not edit */             x: 1183,
/* do not edit */             y: 426,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Marseille",
/* do not edit */             country: "fr",
/* do not edit */             distance: 964,
/* do not edit */             x: 1159,
/* do not edit */             y: 462,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Barcelona",
/* do not edit */             country: "es",
/* do not edit */             distance: 508,
/* do not edit */             x: 1136,
/* do not edit */             y: 481,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Gibraltar",
/* do not edit */             country: "gi",
/* do not edit */             distance: 1108,
/* do not edit */             x: 1104,
/* do not edit */             y: 513,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Marrakesch",
/* do not edit */             country: "ma",
/* do not edit */             distance: 653,
/* do not edit */             x: 1077,
/* do not edit */             y: 548,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Ad Dakhla",
/* do not edit */             country: "eh",
/* do not edit */             distance: 1406,
/* do not edit */             x: 1034,
/* do not edit */             y: 585,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Dakar",
/* do not edit */             country: "sn",
/* do not edit */             distance: 1367,
/* do not edit */             x: 1008,
/* do not edit */             y: 657,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Conakry",
/* do not edit */             country: "gn",
/* do not edit */             distance: 1199,
/* do not edit */             x: 1027,
/* do not edit */             y: 682,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Makeni",
/* do not edit */             country: "sl",
/* do not edit */             distance: 271,
/* do not edit */             x: 1051,
/* do not edit */             y: 690,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Nzerekore",
/* do not edit */             country: "gn",
/* do not edit */             distance: 516,
/* do not edit */             x: 1077,
/* do not edit */             y: 699,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Yamoussoukro",
/* do not edit */             country: "ci",
/* do not edit */             distance: 519,
/* do not edit */             x: 1089,
/* do not edit */             y: 703,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Kumasi",
/* do not edit */             country: "gh",
/* do not edit */             distance: 516,
/* do not edit */             x: 1118,
/* do not edit */             y: 706,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Porto-Novo",
/* do not edit */             country: "bj",
/* do not edit */             distance: 648,
/* do not edit */             x: 1139,
/* do not edit */             y: 708,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Onitsha",
/* do not edit */             country: "ng",
/* do not edit */             distance: 543,
/* do not edit */             x: 1163,
/* do not edit */             y: 710,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Douala",
/* do not edit */             country: "cm",
/* do not edit */             distance: 666,
/* do not edit */             x: 1180,
/* do not edit */             y: 723,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Oyem",
/* do not edit */             country: "ga",
/* do not edit */             distance: 546,
/* do not edit */             x: 1195,
/* do not edit */             y: 740,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Mandilou",
/* do not edit */             country: "ga",
/* do not edit */             distance: 602,
/* do not edit */             x: 1181,
/* do not edit */             y: 756,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Dolisie",
/* do not edit */             country: "cg",
/* do not edit */             distance: 445,
/* do not edit */             x: 1190,
/* do not edit */             y: 770,
/* do not edit */             left: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Kinshasa",
/* do not edit */             country: "cd",
/* do not edit */             distance: 390,
/* do not edit */             x: 1214,
/* do not edit */             y: 773,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Luanda",
/* do not edit */             country: "ao",
/* do not edit */             distance: 818,
/* do not edit */             x: 1205,
/* do not edit */             y: 795,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Lubango",
/* do not edit */             country: "ao",
/* do not edit */             distance: 898,
/* do not edit */             x: 1208,
/* do not edit */             y: 844,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Windhuk",
/* do not edit */             country: "na",
/* do not edit */             distance: 1158,
/* do not edit */             x: 1221,
/* do not edit */             y: 890,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Kapstadt",
/* do not edit */             country: "za",
/* do not edit */             distance: 1479,
/* do not edit */             x: 1230,
/* do not edit */             y: 966,
/* do not edit */             left: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Port Elizabeth",
/* do not edit */             country: "za",
/* do not edit */             distance: 749,
/* do not edit */             x: 1285,
/* do not edit */             y: 969,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Durban",
/* do not edit */             country: "za",
/* do not edit */             distance: 910,
/* do not edit */             x: 1313,
/* do not edit */             y: 949,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Maputo",
/* do not edit */             country: "mz",
/* do not edit */             distance: 542,
/* do not edit */             x: 1323,
/* do not edit */             y: 922,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Harare",
/* do not edit */             country: "zw",
/* do not edit */             distance: 1163,
/* do not edit */             x: 1307,
/* do not edit */             y: 847,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Lilongwe",
/* do not edit */             country: "mw",
/* do not edit */             distance: 817,
/* do not edit */             x: 1324,
/* do not edit */             y: 821,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Dodoma",
/* do not edit */             country: "tz",
/* do not edit */             distance: 1312,
/* do not edit */             x: 1345,
/* do not edit */             y: 778,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Nairobi",
/* do not edit */             country: "ke",
/* do not edit */             distance: 689,
/* do not edit */             x: 1352,
/* do not edit */             y: 750,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Awassa",
/* do not edit */             country: "et",
/* do not edit */             distance: 1273,
/* do not edit */             x: 1368,
/* do not edit */             y: 708,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Dschibuti",
/* do not edit */             country: "dj",
/* do not edit */             distance: 998,
/* do not edit */             x: 1389,
/* do not edit */             y: 676,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Salala",
/* do not edit */             country: "om",
/* do not edit */             distance: 1549,
/* do not edit */             x: 1469,
/* do not edit */             y: 641,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Dubai",
/* do not edit */             country: "ae",
/* do not edit */             distance: 1281,
/* do not edit */             x: 1480,
/* do not edit */             y: 590,
/* do not edit */             left: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Tschahbahar",
/* do not edit */             country: "ir",
/* do not edit */             distance: 667,
/* do not edit */             x: 1516,
/* do not edit */             y: 587,
/* do not edit */             angleCCW: false,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Karatschi",
/* do not edit */             country: "pk",
/* do not edit */             distance: 980,
/* do not edit */             x: 1550,
/* do not edit */             y: 590,
/* do not edit */             angleCCW: false,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Ahmedabad",
/* do not edit */             country: "in",
/* do not edit */             distance: 851,
/* do not edit */             x: 1588,
/* do not edit */             y: 602,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Mumbai",
/* do not edit */             country: "in",
/* do not edit */             distance: 525,
/* do not edit */             x: 1592,
/* do not edit */             y: 628,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Madurai",
/* do not edit */             country: "in",
/* do not edit */             distance: 1427,
/* do not edit */             x: 1626,
/* do not edit */             y: 686,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Kakinada",
/* do not edit */             country: "in",
/* do not edit */             distance: 1123,
/* do not edit */             x: 1660,
/* do not edit */             y: 632,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Kalkutta",
/* do not edit */             country: "in",
/* do not edit */             distance: 1025,
/* do not edit */             x: 1688,
/* do not edit */             y: 607,
/* do not edit */             angleCCW: false,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Mandalay",
/* do not edit */             country: "mm",
/* do not edit */             distance: 1399,
/* do not edit */             x: 1744,
/* do not edit */             y: 612,
/* do not edit */             angleCCW: false,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Rangun",
/* do not edit */             country: "mm",
/* do not edit */             distance: 628,
/* do not edit */             x: 1741,
/* do not edit */             y: 638,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Bangkok",
/* do not edit */             country: "th",
/* do not edit */             distance: 837,
/* do not edit */             x: 1770,
/* do not edit */             y: 657,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Phnom Penh",
/* do not edit */             country: "kh",
/* do not edit */             distance: 719,
/* do not edit */             x: 1793,
/* do not edit */             y: 659,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Pleiku",
/* do not edit */             country: "vn",
/* do not edit */             distance: 627,
/* do not edit */             x: 1816,
/* do not edit */             y: 659,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Hanoi",
/* do not edit */             country: "vn",
/* do not edit */             distance: 1102,
/* do not edit */             x: 1794,
/* do not edit */             y: 618,
/* do not edit */             angleCCW: false,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Hongkong",
/* do not edit */             country: "hk",
/* do not edit */             distance: 1078,
/* do not edit */             x: 1853,
/* do not edit */             y: 605,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Zhangzhou",
/* do not edit */             country: "cn",
/* do not edit */             distance: 713,
/* do not edit */             x: 1873,
/* do not edit */             y: 587,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Fuzhou",
/* do not edit */             country: "cn",
/* do not edit */             distance: 834,
/* do not edit */             x: 1853,
/* do not edit */             y: 562,
/* do not edit */             angleCCW: false,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Shanghai",
/* do not edit */             country: "cn",
/* do not edit */             distance: 771,
/* do not edit */             x: 1900,
/* do not edit */             y: 545,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Peking",
/* do not edit */             country: "cn",
/* do not edit */             distance: 1191,
/* do not edit */             x: 1859,
/* do not edit */             y: 481,
/* do not edit */             angleCCW: false,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Shengyang",
/* do not edit */             country: "cn",
/* do not edit */             distance: 685,
/* do not edit */             x: 1916,
/* do not edit */             y: 459,
/* do not edit */             angleCCW: false,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Wladiwostok",
/* do not edit */             country: "ru",
/* do not edit */             distance: 1095,
/* do not edit */             x: 1967,
/* do not edit */             y: 456,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Chabarowsk",
/* do not edit */             country: "ru",
/* do not edit */             distance: 795,
/* do not edit */             x: 1984,
/* do not edit */             y: 412,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Swobodny",
/* do not edit */             country: "ru",
/* do not edit */             distance: 764,
/* do not edit */             x: 1941,
/* do not edit */             y: 385,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Nerjungri",
/* do not edit */             country: "ru",
/* do not edit */             distance: 851,
/* do not edit */             x: 1913,
/* do not edit */             y: 340,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Jakutsk",
/* do not edit */             country: "ru",
/* do not edit */             distance: 861,
/* do not edit */             x: 1951,
/* do not edit */             y: 293,
/* do not edit */             angleCCW: false,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Sussuman",
/* do not edit */             country: "ru",
/* do not edit */             distance: 1228,
/* do not edit */             x: 2071,
/* do not edit */             y: 285,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Magadan",
/* do not edit */             country: "ru",
/* do not edit */             distance: 626,
/* do not edit */             x: 2089,
/* do not edit */             y: 317,
/* do not edit */             angleCCW: true,
/* do not edit */             isEasternEndpoint: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Anchorage",
/* do not edit */             country: "us",
/* do not edit */             distance: 2832,
/* do not edit */             x: 95,
/* do not edit */             y: 346,
/* do not edit */             isWesternStartpoint: true,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Watson Lake",
/* do not edit */             country: "ca",
/* do not edit */             distance: 1569,
/* do not edit */             x: 272,
/* do not edit */             y: 352,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Prince George",
/* do not edit */             country: "ca",
/* do not edit */             distance: 1323,
/* do not edit */             x: 327,
/* do not edit */             y: 391,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Vancouver",
/* do not edit */             country: "ca",
/* do not edit */             distance: 783,
/* do not edit */             x: 339,
/* do not edit */             y: 427,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Portland",
/* do not edit */             country: "us",
/* do not edit */             distance: 509,
/* do not edit */             x: 339,
/* do not edit */             y: 459,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Sacramento",
/* do not edit */             country: "us",
/* do not edit */             distance: 930,
/* do not edit */             x: 346,
/* do not edit */             y: 512,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Los Angeles",
/* do not edit */             country: "us",
/* do not edit */             distance: 617,
/* do not edit */             x: 369,
/* do not edit */             y: 543,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Phoenix",
/* do not edit */             country: "us",
/* do not edit */             distance: 600,
/* do not edit */             x: 413,
/* do not edit */             y: 548,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Hermosillo",
/* do not edit */             country: "mx",
/* do not edit */             distance: 861,
/* do not edit */             x: 423,
/* do not edit */             y: 569,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Guadalajara",
/* do not edit */             country: "mx",
/* do not edit */             distance: 1355,
/* do not edit */             x: 461,
/* do not edit */             y: 621,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Mexiko Stadt",
/* do not edit */             country: "mx",
/* do not edit */             distance: 553,
/* do not edit */             x: 484,
/* do not edit */             y: 635,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Oaxaca",
/* do not edit */             country: "mx",
/* do not edit */             distance: 462,
/* do not edit */             x: 500,
/* do not edit */             y: 648,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Guatemala Stadt",
/* do not edit */             country: "gt",
/* do not edit */             distance: 986,
/* do not edit */             x: 535,
/* do not edit */             y: 660,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Tegucigalpa",
/* do not edit */             country: "hn",
/* do not edit */             distance: 651,
/* do not edit */             x: 559,
/* do not edit */             y: 668,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Managua",
/* do not edit */             country: "ni",
/* do not edit */             distance: 366,
/* do not edit */             x: 568,
/* do not edit */             y: 678,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "San José",
/* do not edit */             country: "cr",
/* do not edit */             distance: 424,
/* do not edit */             x: 578,
/* do not edit */             y: 693,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Panama City",
/* do not edit */             country: "pa",
/* do not edit */             distance: 851,
/* do not edit */             x: 609,
/* do not edit */             y: 703,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Medellin",
/* do not edit */             country: "co",
/* do not edit */             distance: 494,
/* do not edit */             x: 637,
/* do not edit */             y: 718,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Quito",
/* do not edit */             country: "ec",
/* do not edit */             distance: 1183,
/* do not edit */             x: 614,
/* do not edit */             y: 757,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Guayaquil",
/* do not edit */             country: "ec",
/* do not edit */             distance: 421,
/* do not edit */             x: 607,
/* do not edit */             y: 769,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Sullana",
/* do not edit */             country: "pe",
/* do not edit */             distance: 451,
/* do not edit */             x: 600,
/* do not edit */             y: 785,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Lima",
/* do not edit */             country: "pe",
/* do not edit */             distance: 1019,
/* do not edit */             x: 623,
/* do not edit */             y: 827,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "La Paz",
/* do not edit */             country: "bo",
/* do not edit */             distance: 1517,
/* do not edit */             x: 675,
/* do not edit */             y: 853,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Antofagasta",
/* do not edit */             country: "cl",
/* do not edit */             distance: 1116,
/* do not edit */             x: 670,
/* do not edit */             y: 893,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Santiago de Chile",
/* do not edit */             country: "cl",
/* do not edit */             distance: 1335,
/* do not edit */             x: 664,
/* do not edit */             y: 968,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Bariloche",
/* do not edit */             country: "ar",
/* do not edit */             distance: 1155,
/* do not edit */             x: 653,
/* do not edit */             y: 1021,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Rio Gallegos",
/* do not edit */             country: "ar",
/* do not edit */             distance: 1539,
/* do not edit */             x: 680,
/* do not edit */             y: 1099,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Comodo Rivadavia",
/* do not edit */             country: "ar",
/* do not edit */             distance: 779,
/* do not edit */             x: 692,
/* do not edit */             y: 1058,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Bahia Blanca",
/* do not edit */             country: "ar",
/* do not edit */             distance: 1093,
/* do not edit */             x: 729,
/* do not edit */             y: 1011,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Buenos Aires",
/* do not edit */             country: "ar",
/* do not edit */             distance: 635,
/* do not edit */             x: 752,
/* do not edit */             y: 987,
/* do not edit */             left: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Montevideo",
/* do not edit */             country: "uy",
/* do not edit */             distance: 184,
/* do not edit */             x: 764,
/* do not edit */             y: 982,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Porto Alegre",
/* do not edit */             country: "br",
/* do not edit */             distance: 789,
/* do not edit */             x: 797,
/* do not edit */             y: 941,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Curtiba",
/* do not edit */             country: "br",
/* do not edit */             distance: 684,
/* do not edit */             x: 809,
/* do not edit */             y: 916,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Sao Paulo",
/* do not edit */             country: "br",
/* do not edit */             distance: 417,
/* do not edit */             x: 833,
/* do not edit */             y: 902,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Rio de Janeiro",
/* do not edit */             country: "br",
/* do not edit */             distance: 434,
/* do not edit */             x: 855,
/* do not edit */             y: 892,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Vitória",
/* do not edit */             country: "br",
/* do not edit */             distance: 524,
/* do not edit */             x: 867,
/* do not edit */             y: 869,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Salvador",
/* do not edit */             country: "br",
/* do not edit */             distance: 1167,
/* do not edit */             x: 870,
/* do not edit */             y: 827,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Recife",
/* do not edit */             country: "br",
/* do not edit */             distance: 805,
/* do not edit */             x: 896,
/* do not edit */             y: 801,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Fortaleza",
/* do not edit */             country: "br",
/* do not edit */             distance: 759,
/* do not edit */             x: 868,
/* do not edit */             y: 772,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Sao Luis",
/* do not edit */             country: "br",
/* do not edit */             distance: 900,
/* do not edit */             x: 831,
/* do not edit */             y: 772,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Belèm",
/* do not edit */             country: "br",
/* do not edit */             distance: 580,
/* do not edit */             x: 806,
/* do not edit */             y: 758,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Macapá",
/* do not edit */             country: "br",
/* do not edit */             distance: 333,
/* do not edit */             x: 794,
/* do not edit */             y: 746,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Cayenne",
/* do not edit */             country: "gf",
/* do not edit */             distance: 333,
/* do not edit */             x: 781,
/* do not edit */             y: 720,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Paramaribo",
/* do not edit */             country: "sr",
/* do not edit */             distance: 333,
/* do not edit */             x: 762,
/* do not edit */             y: 711,
/* do not edit */             angleCCW: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Georgetown",
/* do not edit */             country: "gy",
/* do not edit */             distance: 444,
/* do not edit */             x: 737,
/* do not edit */             y: 706,
/* do not edit */             angleCCW: false,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Caracas",
/* do not edit */             country: "ve",
/* do not edit */             distance: 1044,
/* do not edit */             x: 681,
/* do not edit */             y: 688,
/* do not edit */             left: true,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Port au Prince",
/* do not edit */             country: "ht",
/* do not edit */             distance: 520,
/* do not edit */             x: 662,
/* do not edit */             y: 643,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Havanna",
/* do not edit */             country: "cu",
/* do not edit */             distance: 880,
/* do not edit */             x: 596,
/* do not edit */             y: 609,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Miami",
/* do not edit */             country: "us",
/* do not edit */             distance: 1068,
/* do not edit */             x: 602,
/* do not edit */             y: 585,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Atlanta",
/* do not edit */             country: "us",
/* do not edit */             distance: 711,
/* do not edit */             x: 573,
/* do not edit */             y: 538,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Charlotte",
/* do not edit */             country: "us",
/* do not edit */             distance: 268,
/* do not edit */             x: 600,
/* do not edit */             y: 520,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Washington",
/* do not edit */             country: "us",
/* do not edit */             distance: 405,
/* do not edit */             x: 628,
/* do not edit */             y: 487,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "New York City",
/* do not edit */             country: "us",
/* do not edit */             distance: 241,
/* do not edit */             x: 653,
/* do not edit */             y: 477,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Bangor",
/* do not edit */             country: "us",
/* do not edit */             distance: 481,
/* do not edit */             x: 671,
/* do not edit */             y: 451,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Rigolet",
/* do not edit */             country: "ca",
/* do not edit */             distance: 1280,
/* do not edit */             x: 736,
/* do not edit */             y: 373,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Nanortalik",
/* do not edit */             country: "gl",
/* do not edit */             distance: 1028,
/* do not edit */             x: 807,
/* do not edit */             y: 319,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Ammassalik",
/* do not edit */             country: "gl",
/* do not edit */             distance: 720,
/* do not edit */             x: 876,
/* do not edit */             y: 270,
/* do not edit */             angleCCW: false,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Reykjavík",
/* do not edit */             country: "is",
/* do not edit */             distance: 757,
/* do not edit */             x: 963,
/* do not edit */             y: 282,
/* do not edit */             angleCCW: false,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Neskaupstaður",
/* do not edit */             country: "is",
/* do not edit */             distance: 703,
/* do not edit */             x: 1024,
/* do not edit */             y: 271,
/* do not edit */             angleCCW: false,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Bodø",
/* do not edit */             country: "no",
/* do not edit */             distance: 1269,
/* do not edit */             x: 1213,
/* do not edit */             y: 255,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Trondheim",
/* do not edit */             country: "no",
/* do not edit */             distance: 704,
/* do not edit */             x: 1188,
/* do not edit */             y: 289,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Lillehammer",
/* do not edit */             country: "no",
/* do not edit */             distance: 352,
/* do not edit */             x: 1191,
/* do not edit */             y: 311,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Oslo",
/* do not edit */             country: "no",
/* do not edit */             distance: 185,
/* do not edit */             x: 1193,
/* do not edit */             y: 329,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Göteborg",
/* do not edit */             country: "se",
/* do not edit */             distance: 328,
/* do not edit */             x: 1199,
/* do not edit */             y: 347,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Kopenhagen",
/* do not edit */             country: "dk",
/* do not edit */             distance: 307,
/* do not edit */             x: 1198,
/* do not edit */             y: 357,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Hamburg",
/* do not edit */             country: "de",
/* do not edit */             distance: 338,
/* do not edit */             x: 1188,
/* do not edit */             y: 384,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Würzburg",
/* do not edit */             country: "de",
/* do not edit */             distance: 518,
/* do not edit */             x: 1189,
/* do not edit */             y: 409,
/* do not edit */         },
/* do not edit */         {
/* do not edit */             name: "Kempten",
/* do not edit */             country: "de",
/* do not edit */             distance: 268,
/* do not edit */             x: 1183,
/* do not edit */             y: 426,
/* do not edit */             image: "de_kempten_2.jpg",
/* do not edit */         },
/* do not edit */     ];
/* do not edit */
/* do not edit */     export const countries: Country[] = [
/* do not edit */         {
/* do not edit */             code: "de",
/* do not edit */             name: "Deutschland"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "fr",
/* do not edit */             name: "Frankreich"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "it",
/* do not edit */             name: "Italien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "es",
/* do not edit */             name: "Spanien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gi",
/* do not edit */             name: "Gibraltar"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ma",
/* do not edit */             name: "Marokko"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "eh",
/* do not edit */             name: "Westsahara"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "sn",
/* do not edit */             name: "Senegal"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gn",
/* do not edit */             name: "Guinea"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "sl",
/* do not edit */             name: "Sierra Leone"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ci",
/* do not edit */             name: "Cote d`Ivoir"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gh",
/* do not edit */             name: "Ghana"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "bj",
/* do not edit */             name: "Benin"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ng",
/* do not edit */             name: "Nigeria"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cm",
/* do not edit */             name: "Kamerun"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ga",
/* do not edit */             name: "Gabun"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cg",
/* do not edit */             name: "Kongo"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cd",
/* do not edit */             name: "D. R. Kongo"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "vn",
/* do not edit */             name: "Vietnam"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "kh",
/* do not edit */             name: "Kambodscha"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "th",
/* do not edit */             name: "Thailand"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "mm",
/* do not edit */             name: "Myanmar"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "in",
/* do not edit */             name: "Indien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "pk",
/* do not edit */             name: "Pakistan"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ir",
/* do not edit */             name: "Iran"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ae",
/* do not edit */             name: "Ver. arab. Emirate"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "om",
/* do not edit */             name: "Oman"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "dj",
/* do not edit */             name: "Dschibouti"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "et",
/* do not edit */             name: "Äthiopien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ao",
/* do not edit */             name: "Angola"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "na",
/* do not edit */             name: "Namibia"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "za",
/* do not edit */             name: "Südafrika"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "mz",
/* do not edit */             name: "Mosambik"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "zw",
/* do not edit */             name: "Simbabwe"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "mw",
/* do not edit */             name: "Malawi"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "tz",
/* do not edit */             name: "Tansania"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ke",
/* do not edit */             name: "Kenia"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "hk",
/* do not edit */             name: "Hongkong"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cn",
/* do not edit */             name: "China"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ru",
/* do not edit */             name: "Russland"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "us",
/* do not edit */             name: "USA"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ca",
/* do not edit */             name: "Kanada"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "mx",
/* do not edit */             name: "Mexiko"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gt",
/* do not edit */             name: "Guatemala"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "hn",
/* do not edit */             name: "Honduras"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ni",
/* do not edit */             name: "Nicaragua"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cr",
/* do not edit */             name: "Costa Rica"
/* do not edit */         },
/* do not edit */
/* do not edit */         {
/* do not edit */             code: "pa",
/* do not edit */             name: "Panama"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "co",
/* do not edit */             name: "Kolumbien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ec",
/* do not edit */             name: "Ecuador"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "pe",
/* do not edit */             name: "Peru"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "bo",
/* do not edit */             name: "Bolivien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cl",
/* do not edit */             name: "Chile"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ar",
/* do not edit */             name: "Argentinien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "uy",
/* do not edit */             name: "Uruguay"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "br",
/* do not edit */             name: "Brasilien"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gf",
/* do not edit */             name: "Franz. Guyana"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "sr",
/* do not edit */             name: "Suriname"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gy",
/* do not edit */             name: "Guyana"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ve",
/* do not edit */             name: "Venezuela"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "ht",
/* do not edit */             name: "Haiti"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "cu",
/* do not edit */             name: "Kuba"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "gl",
/* do not edit */             name: "Grönland"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "is",
/* do not edit */             name: "Island"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "no",
/* do not edit */             name: "Norwegen"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "se",
/* do not edit */             name: "Schweden"
/* do not edit */         },
/* do not edit */         {
/* do not edit */             code: "dk",
/* do not edit */             name: "Dänemark"
/* do not edit */         },
/* do not edit */
/* do not edit */     ];
/* do not edit */ }
