name: Build

on: [push]

jobs:
  build_api:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    name: API on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install dependencies
      working-directory: api
      run: npm i
    - name: Create files with api keys
      working-directory: api
      run: npm run createFilesWithApiKeys
    - name: Build
      working-directory: api
      run: npm run build
  build_web:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    name: Web on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install dependencies
      working-directory: AGtiv
      run: npm i
    - name: Build
      working-directory: AGtiv
      run: npm run build